[project]
name = "tep-classifier-poc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "gliner2>=1.0.2",
    "sieves>=0.21.0",
    "transformers>=4.57.1",
]
